export const SET_THEME = "SET_THEME";

export const SET_AUDIO_PREFERENCE = "SET_AUDIO_PREFERENCE";

export const SET_ACCEPT_APP = "SET_ACCEPT_APP";

export const SET_SHOW_APP = "SET_SHOW_APP";

export const SET_ENABLE_PARTICLES = "SET_ENABLE_PARTICLES";
